### ISSUE TITLE
开机HDMI失效

### ISSUE THREAD

**Issue by caiisen** [taizilongxu/hackintosh_b360i_i5_9600k#1]
我的配置是strix b360i，i5 8400，无独显，在HDMI下直接使用EFI在开机之后要输密码的时候黑屏无信号，需拔插一次HDMI接口才能重新显示。能否提供一些能完美的思路

**Comment by taizilongxu** [comment]
这个我暂时没遇到啊, 我这个配置连 HDPI 和 DP 都是正常的

**Comment by taizilongxu** [comment]
这个要输入密码的时候黑屏说明系统已经可以正常识别 hdmi, 换一个 HDMI 线或者显示器看看呢

**Comment by caiisen** [comment]
感谢你的建议，我会去尝试一下
